language: ruby
rvm:
  - "2.3.0"
cache: bundler
before_script:
  - psql -c 'create database apipair_test;' -U postgres
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare

script: bundle exec xvfb-run rspec spec
